### ISSUE TITLE
filter groupby returning only 100 rows

### ISSUE THREAD

**Issue by robomotic** [alkemics/pandagg#72]
Hi there,
I have a simple aggregation query:

```
from datetime import datetime
import pandas as pd

start = datetime.now()

search = oneday\
    .search()\
    .filter('term',EventID=4688)\
    .groupby('LogHost.keyword')\
    .groupby('ProcessName.keyword')
    
response = search.execute()
aday_host_proc =response.aggregations.to_dataframe()
end = datetime.now()
time_taken = end - start
print('Time: ',time_taken) 
```

<Response> took 3786ms, success: True, total result >=10000, contains 10 hits

The dataframe returned has only 100 rows, there are obviously many more results, but from the documentation it is unclear about how do to that.

Cheers!

**Comment by robomotic** [comment]
For instance even if I change the size like this:

```
search = oneday\
    .search().size(1000)\
    .filter('term',EventID=4688)\
    .groupby('LogHost.keyword')\
    .groupby('ProcessName.keyword')
```

This: aday_host_proc.shape is still 100.
but the response is correct:
<Response> took 4205ms, success: True, total result >=10000, contains 1000 hits

**Comment by robomotic** [comment]
okay for clarification the size parameter is related to the actual size of the search result and not the aggregations.
I have been reading about aggregations and the inability to perform scroll operations which is a limitation of the actual engine, but I am still puzzled by the hard limit at 100, can't find anything in the code in relation to it.

**Comment by alk-lbinet** [comment]
Hi @robomotic 

Indeed, the `size` method will update `size` parameter in search query, cf https://www.elastic.co/guide/en/elasticsearch/reference/7.13/paginate-search-results.html#paginate-search-results
which correspond to the number of returned documents.

For aggregations, the number of returned terms in a `terms` aggregation defaults to 10, cf https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-size

Since you are nesting 2 terms aggregation clauses using the `groupby` method, the aggregation will result in 10 `LogHost.keyword` terms, each of them containing 10 `ProcessName.keyword`. This will result in 10x10=100 lines in tabular formatting.

You can control the size parameter of `terms` aggregation using `size` keyword parameter in your query, for instance:

```
search = oneday\
    .search()\
    .size(0)\
    .filter('term',EventID=4688)\
    .groupby('LogHost.keyword', size=100)\
    .groupby('ProcessName.keyword', size=100)
```
which would result in at most 100x100 = 10000 lines.

Note: I set search `size` to 0 since you do not seem to be using documents response, rather only the `aggregation` part.

Cheers,

Léonard

**Comment by robomotic** [comment]
That makes perfect sense now!
Reading from your link there is also a mention to Composite queries that allows pagination and avoids guessing the size quantity.
Do you have any plans to support that too ?

**Comment by alk-lbinet** [comment]
Indeed, I'll prioritize the composition aggregation feature, maybe next week if I find some time

**Comment by robomotic** [comment]
This is what is reported via pip info:

```
Name: pandagg
Version: 0.2.0
Summary: Python package provided to make elasticsearch aggregations and queries easy.
Home-page: https://github.com/alkemics/pandagg
Author: Léonard Binet
Author-email: leonardbinet@gmail.com
License: Apache-2.0
Location: /home/jovyan/.local/lib/python3.8/site-packages
Requires: elasticsearch, lighttree, six, future
Required-by: 
```

**Comment by robomotic** [comment]
This is after I install the version via git clone (removing the old one first):

```
Name: pandagg
Version: 0.2.0
Summary: Python package provided to make elasticsearch aggregations and queries easy.
Home-page: https://github.com/alkemics/pandagg
Author: Léonard Binet
Author-email: leonardbinet@gmail.com
License: Apache-2.0
Location: /opt/conda/lib/python3.8/site-packages/pandagg-0.2.0-py3.8.egg
Requires: six, future, lighttree, elasticsearch
Required-by: 
```

Did you forget to bump the file version maybe?

**Comment by alk-lbinet** [comment]
@robomotic I see 2 potential reasons:
- either your request is not fully executed until you reach the timeout, in this case increase timeout when instanciating `elasticsearch.Elasticsearch` client
- either your cluster cannot handle such an heavy request, in that case you should use `composite` aggregations to iterate over buckets rather than getting them all at once. unfortunately I haven't had time to implement it in `pandagg` yet (it's definitely in my priorities though)

**Comment by priamai** [comment]
Very good points, the exceptions was a bit misleading, I will try with the timeout increase.
The composite will be awesome to have looking forward to it.

**Comment by alk-lbinet** [comment]
Actually, another possibility is that you reached your `max-buckets` limit (cluster setting that defaults to 65k): https://www.elastic.co/guide/en/elasticsearch/reference/current/search-settings.html#search-settings-max-buckets

**Comment by priamai** [comment]
That could be also definitely since I have more than 65k distinct terms, didn't know it!

**Comment by alk-lbinet** [comment]
(this will be solved with use of `composite` agg)

**Comment by alk-lbinet** [comment]
closing now that composite aggs pagination is supported (v0.2.3)
